/* SPDX-License-Identifier: GPL-3.0-or-later */
/*
 * NES / Famicom (Ricoh 2A03 = 6502 / cc65) — Royal Game of Ur.
 *
 * Reuses the portable core (src/common/ur) unchanged; this is the thin platform
 * layer. There is NO FujiNet for the NES, so this is a LOCAL build (hot-seat +
 * vs-AI), like the ColecoVision cartridge.
 *
 * Renderer: a custom CHR-tile board, NOT cc65's conio. We take over the PPU
 * directly (NMI stays OFF; updates happen in forced blank) and draw the shared
 * horizontal 3x8 Standard-of-Ur board from carved CHR cells (src/nes/chr.s,
 * generated by tools/nes-chr.c): gold flower rosettes, gold bullseye eyes down the
 * shared lane, white quincunx on the private lanes, and round two-tone tokens —
 * each cell a 2x2-tile (16x16) block aligned to the attribute grid so it gets its
 * own palette. The HUD uses an 8x8 font baked into the same CHR (placed at ASCII
 * codes, so put_str writes characters straight through). Input is the NES
 * controller, read off $4016.
 *
 * Build: cc65 -t nes (see makefiles/nes.mk); run in MAME (nes) / Mesen / FCEUX.
 */
#include <stdint.h>
#include <stdbool.h>
#include <nes.h>

#include "ur.h"
#include "ur_game.h"        /* shared local-game controller + plat.h interface */
#include "music.h"          /* the Hurrian Hymn title theme (shared melody) */
#include "sound.h"

#define NO_ROLL 0xFF

/* ---- NES controller ($4016) ------------------------------------------------ */
#define JOYPAD1 (*(volatile unsigned char *)0x4016)
#define PAD_A      0x80
#define PAD_B      0x40
#define PAD_SELECT 0x20
#define PAD_START  0x10
#define PAD_UP     0x08
#define PAD_DOWN   0x04
#define PAD_LEFT   0x02
#define PAD_RIGHT  0x01

static unsigned char read_pad_raw(void)
{
    unsigned char i, v = 0;
    JOYPAD1 = 1; JOYPAD1 = 0;                 /* strobe */
    for (i = 0; i < 8; i++)
        v = (unsigned char)((v << 1) | (JOYPAD1 & 1));
    return v;
}
/* DMA-safe read: re-read until two consecutive reads agree (guards against the
 * controller-read corruption a mid-read DMA/IRQ can cause). */
static unsigned char read_pad(void)
{
    unsigned char a, b;
    a = read_pad_raw();
    do { b = a; a = read_pad_raw(); } while (a != b);
    return a;
}

/* ---- PPU / screen buffer --------------------------------------------------- */
static unsigned char scr[960];        /* nametable tiles  */
static unsigned char attrb[64];       /* attribute table  */

/* 4 background palettes (+ 4 unused sprite palettes). Colour 0 is the shared lapis
 * backdrop. P0 white (text/quincunx), P1 gold+white (rosette/eye); the tokens use the
 * authentic Standard-of-Ur materials — P2 shell-white Light, P3 carnelian-red Dark —
 * which read cleanly against each other and against the gold cells. */
static const unsigned char palette[32] = {
    0x01, 0x30, 0x28, 0x0F,   /* P0: lapis, white,  gold,  black */
    0x01, 0x28, 0x30, 0x17,   /* P1: lapis, gold,   white, brown  -> rosette/eye */
    0x01, 0x30, 0x16, 0x16,   /* P2: lapis, shell-white, carnelian -> Light token */
    0x01, 0x16, 0x30, 0x30,   /* P3: lapis, carnelian,  shell-white -> Dark token */
    0x01, 0x30, 0x28, 0x16,   0x01, 0,0,0,   0x01, 0,0,0,   0x01, 0,0,0
};

/* board cell CHR bases (each a 2x2 block) + their palette */
#define T_ROSE  0xC0
#define T_EYE   0xC4
#define T_DOTS  0xC8
#define T_LIGHT 0xCC
#define T_DARK  0xD0
#define P_TEXT  0
#define P_GOLD  1
#define P_LIGHT 2
#define P_DARK  3

#define BX 8                  /* board origin, in tiles (even for attr alignment) */
#define BY 8

static void vwait(void) { while (!(PPU.status & 0x80)) {} }

/* Push the screen buffer to VRAM in forced blank, then turn rendering back on. */
static void ppu_blit(void)
{
    unsigned int i;
    vwait();
    PPU.mask = 0x00;                       /* rendering off -> VRAM free */
    PPU.control = 0x00;                    /* NMI off, BG pattern table $0000 */
    (void)PPU.status;                      /* reset address latch */
    PPU.vram.address = 0x3F; PPU.vram.address = 0x00;
    for (i = 0; i < 32; i++) PPU.vram.data = palette[i];
    PPU.vram.address = 0x20; PPU.vram.address = 0x00;
    for (i = 0; i < 960; i++) PPU.vram.data = scr[i];
    for (i = 0; i < 64;  i++) PPU.vram.data = attrb[i];
    (void)PPU.status;
    PPU.scroll = 0; PPU.scroll = 0;
    PPU.control = 0x00;
    PPU.mask = 0x0A;                       /* show BG (+ leftmost column) */
}

static void clear_screen(void)
{
    unsigned int i;
    for (i = 0; i < 960; i++) scr[i] = 0x20;   /* blank tile -> lapis field */
    for (i = 0; i < 64;  i++) attrb[i] = 0;
}

static void put_str(unsigned char tx, unsigned char ty, const char *s)
{
    unsigned int o = (unsigned int)ty * 32 + tx;
    while (*s) scr[o++] = (unsigned char)*s++;
}

static void set_attr(unsigned char col, unsigned char row, unsigned char pal)
{
    unsigned char tx = (unsigned char)(BX + col * 2), ty = (unsigned char)(BY + row * 2);
    unsigned char idx = (unsigned char)((ty >> 2) * 8 + (tx >> 2));
    unsigned char shift = (unsigned char)(((((ty >> 1) & 1) << 1) | ((tx >> 1) & 1)) << 1);
    attrb[idx] = (unsigned char)((attrb[idx] & ~(3 << shift)) | (pal << shift));
}

/* Draw a 2x2 board cell (TL,TR,BL,BR = base..base+3) + its palette. */
static void put_cell(unsigned char col, unsigned char row,
                     unsigned char base, unsigned char pal)
{
    unsigned int o = (unsigned int)(BY + row * 2) * 32 + (BX + col * 2);
    scr[o]      = base;
    scr[o + 1]  = (unsigned char)(base + 1);
    scr[o + 32] = (unsigned char)(base + 2);
    scr[o + 33] = (unsigned char)(base + 3);
    set_attr(col, row, pal);
}

/* ---- small number/string helpers ------------------------------------------ */
static char *put_s(char *p, const char *s) { while (*s) *p++ = *s++; return p; }
static char *put_u(char *p, unsigned char v)
{
    if (v >= 100) { *p++ = (char)('0' + v / 100); v = (unsigned char)(v % 100);
                    *p++ = (char)('0' + v / 10);  *p++ = (char)('0' + v % 10); }
    else if (v >= 10) { *p++ = (char)('0' + v / 10); *p++ = (char)('0' + v % 10); }
    else *p++ = (char)('0' + v);
    return p;
}

/* ---- board geometry (shared horizontal mapping) --------------------------- */
static bool pos_to_cell(unsigned char player, unsigned char pos,
                        unsigned char *row, unsigned char *col)
{
    if (pos < 1 || pos > 14) return false;
    if (pos <= 4)       { *row = player ? 2 : 0; *col = (unsigned char)(4 - pos); }
    else if (pos <= 12) { *row = 1;              *col = (unsigned char)(pos - 5); }
    else                { *row = player ? 2 : 0; *col = (pos == 13) ? 7 : 6; }
    return true;
}
static bool is_rosette_cell(unsigned char row, unsigned char col)
{
    if (row == 1) return col == 3;
    return col == 0 || col == 6;
}
static bool cell_exists(unsigned char row, unsigned char col)
{
    if (row == 1) return true;
    return col <= 3 || col >= 6;
}

static uint16_t g_seed = 0xACE1u;   /* RNG entropy (accumulated during the menu) */

/* Build the board + HUD into the screen buffer (no blit). */
static void build_board(unsigned char roll, const char *msg)
{
    unsigned char row, col, pl, i, pos, rr, cc;
    char grid[3][8];          /* 0 cut, 'L'/'D' token, '*' rosette, 'E' eye, '.' dots */
    char buf[24], *p;

    clear_screen();
    put_str(8, 2, "ROYAL GAME OF UR");

    for (row = 0; row < 3; row++)
        for (col = 0; col < 8; col++)
            grid[row][col] = cell_exists(row, col)
                           ? (is_rosette_cell(row, col) ? '*' : (row == 1 ? 'E' : '.'))
                           : 0;
    for (pl = 0; pl < UR_NUM_PLAYERS; pl++)
        for (i = 0; i < UR_PIECES; i++) {
            pos = ur_g.piece[pl][i];
            if (pos_to_cell(pl, pos, &rr, &cc))
                grid[rr][cc] = pl ? 'D' : 'L';
        }

    for (row = 0; row < 3; row++)
        for (col = 0; col < 8; col++) {
            char g = grid[row][col];
            if (g == 0)        continue;                        /* cut-away: field */
            else if (g == '*') put_cell(col, row, T_ROSE,  P_GOLD);
            else if (g == 'E') put_cell(col, row, T_EYE,   P_GOLD);
            else if (g == '.') put_cell(col, row, T_DOTS,  P_TEXT);
            else if (g == 'L') put_cell(col, row, T_LIGHT, P_LIGHT);
            else               put_cell(col, row, T_DARK,  P_DARK);
        }

    put_str(2, 16, ur_g.turn ? "TURN: DARK" : "TURN: LIGHT");
    p = put_s(buf, "LIGHT:");
    p = put_u(p, (unsigned char)ur_score(&ur_g, 0));
    p = put_s(p, " DARK:");
    p = put_u(p, (unsigned char)ur_score(&ur_g, 1));
    *p = 0;
    put_str(2, 17, buf);
    if (roll != NO_ROLL) { p = put_s(buf, "ROLL:"); p = put_u(p, roll); *p = 0; put_str(2, 18, buf); }
    if (msg) put_str(2, 27, msg);
}

/* plat.h: draw the board + HUD + message for the active game. */
void plat_draw(unsigned char roll, const char *msg)
{
    build_board(roll, msg);
    ppu_blit();
}

/* Block until a fresh button press (full release first). */
static unsigned char wait_pad(void)
{
    unsigned char p;
    while (read_pad()) {}
    for (;;) { p = read_pad(); if (p) return p; }
}

/* plat.h: wait for one confirm press. */
void plat_wait(void) { wait_pad(); }

/* plat.h: list legal moves (deduped by source); pick one with Up/Down + A. The
 * board for `roll` is already drawn (by the controller), so we add the prompt +
 * list on top (the screen buffer persists between blits). */
#define MLY 20
int8_t plat_choose_move(unsigned char player, unsigned char roll)
{
    unsigned char pieces[UR_PIECES], srcs[UR_PIECES];
    unsigned char count, nsrc, i, j, pos, dest, sel, pad;
    bool seen;

    count = ur_legal_moves(&ur_g, player, roll, pieces);
    if (count == 0) return -1;

    nsrc = 0;
    for (i = 0; i < count; i++) {
        pos = ur_g.piece[player][pieces[i]];
        seen = false;
        for (j = 0; j < nsrc; j++) if (srcs[j] == pos) { seen = true; break; }
        if (!seen) srcs[nsrc++] = pos;
    }

    put_str(2, 27, "UP DOWN + A");
    for (i = 0; i < nsrc; i++) {                   /* move list lines */
        char buf[12], *p = buf;
        pos = srcs[i];
        dest = (unsigned char)(pos + roll);
        if (pos == UR_POS_START) *p++ = 'E'; else p = put_u(p, pos);
        *p++ = '>';
        p = put_u(p, dest);
        if (dest == UR_POS_HOME)      *p++ = 'H';
        else if (ur_is_rosette(dest)) *p++ = '*';
        else if (ur_dest_captures(&ur_g, player, dest)) *p++ = 'X';   /* capture */
        *p = 0;
        put_str(3, (unsigned char)(MLY + i), buf);
    }

    sel = 0;
    for (;;) {
        for (i = 0; i < nsrc; i++)                 /* selector cursor */
            scr[(unsigned int)(MLY + i) * 32 + 1] = (i == sel) ? '>' : 0x20;
        ppu_blit();
        pad = wait_pad();
        if ((pad & PAD_UP) && sel > 0) sel--;
        else if ((pad & PAD_DOWN) && sel + 1 < nsrc) sel++;
        else if (pad & (PAD_A | PAD_START)) break;
    }

    pos = srcs[sel];
    for (i = 0; i < count; i++)
        if (ur_g.piece[player][pieces[i]] == pos) return (int8_t)pieces[i];
    return (int8_t)pieces[0];
}

/* plat.h: sound + RNG entropy. The shared controller (ur_game.c) owns the turn
 * loop and calls these; g_seed is accumulated while the menu waits for input. */
void plat_roll(uint8_t roll) { (void)roll; sfx_roll(); }
void plat_sfx_result(const ur_move_result *res) { sfx_for_result(res); }
uint16_t plat_seed(void) { return g_seed; }
void plat_animate(uint8_t player, uint8_t from, uint8_t to) { (void)player; (void)from; (void)to; }

/* plat.h: choose the AI difficulty (D-pad Up = Easy, Down = Hard, A = Normal). */
uint8_t plat_pick_level(void)
{
    unsigned char p;
    clear_screen();
    put_str(8, 4, "DIFFICULTY");
    put_str(6, 9,  "UP   - EASY");
    put_str(6, 11, "A    - NORMAL");
    put_str(6, 13, "DOWN - HARD");
    ppu_blit();
    for (;;) {
        p = wait_pad();
        if (p & PAD_UP)               return UR_AI_EASY;
        if (p & PAD_DOWN)             return UR_AI_HARD;
        if (p & (PAD_A | PAD_B | PAD_START)) return UR_AI_NORMAL;
    }
}

/* Show the end-of-game result on the board, then wait. */
static void show_win(uint8_t winner, bool ai1)
{
    build_board(NO_ROLL, (const char *)0);
    if (ai1) put_str(2, 22, winner == 0 ? "YOU WIN" : "YOU LOSE");
    else     put_str(2, 22, winner == 0 ? "LIGHT WINS" : "DARK WINS");
    put_str(2, 24, "PRESS A");
    ppu_blit();
    wait_pad();
}

/* Title music: the Hurrian Hymn, played once at boot. Skippable — returns as soon
 * as a button is pressed (left for the menu), so the player can start immediately. */
static bool g_played_music = false;
static void play_hymn(void)
{
    uint16_t i;
    if (g_played_music) return;
    g_played_music = true;
    for (i = 0; i < ur_hymn_len; i++) {
        if (read_pad()) { snd_silence(); return; }
        nes_music_note(ur_hymn[i].note, ur_hymn[i].dur);
    }
    snd_silence();
}

int main(void)
{
    unsigned char pad;

    PPU.control = 0x00;            /* NMI off */
    PPU.mask = 0x00;
    vwait(); vwait();              /* PPU warm-up */
    nes_sound_init();

    for (;;) {
        clear_screen();
        put_str(8, 3, "ROYAL GAME OF UR");
        put_str(12, 5, "NES");
        put_str(6, 10, "A - TWO PLAYERS");
        put_str(6, 12, "B - VS COMPUTER");
        put_str(6, 15, "D-PAD + A: MOVES");
        put_str(6, 20, "PRESS A OR B");
        put_str(4, 26, "RULES: DR FINKEL");
        ppu_blit();

        play_hymn();                       /* the Hurrian Hymn (once, skippable) */
        while (!read_pad()) g_seed++;      /* entropy from wait time -> plat_seed() */
        pad = wait_pad();
        if (pad & (PAD_A | PAD_B))         /* A = two players, B = vs computer */
            show_win(ur_run_game((pad & PAD_B) ? 1 : 0), (pad & PAD_B) != 0);
    }
    return 0;
}
