/* SPDX-License-Identifier: GPL-3.0-or-later */
/*
 * Host tool: generate the Coleco Adam / ColecoVision 16x16 carved-cell glyphs.
 *
 * The board is horizontal (3 rows x 8 cols), like the SMS — so each square is a
 * 16x16 (2x2-char) carved TMS9928A Graphics-II cell, and the pieces are charset
 * donut tokens (the TMS 4-sprites-per-scanline limit rules out a dense row of
 * 16x16 sprite tokens, so we draw them as cells too, like the C64/Atari). Each
 * cell is 4 custom 8x8 patterns laid out TL,TR,BL,BR (carve_cell writes them in
 * that order); a pattern byte is one pixel row, MSB = leftmost pixel. TMS cells
 * are 2-colour (one FG + one BG per char), so each glyph is just the FG mask.
 *
 * Emits the byte arrays for src/adam/main.c. Build + run:
 *   cc -o gen tools/adam-mosaic-glyphs.c && ./gen
 */
#include <stdio.h>

static int B[16][16];

static void clear(void)
{
    int x, y;
    for (y = 0; y < 16; y++)
        for (x = 0; x < 16; x++)
            B[y][x] = 0;
}

/* Pack the 16x16 bitmap into 4 chars (TL,TR,BL,BR), MSB = leftmost pixel. */
static void emit(const char *nm, const char *comment)
{
    const char *lab[4] = { "TL", "TR", "BL", "BR" };
    int q, r, x, b, ox, oy;
    printf("static const unsigned char g_%s[32] = {   /* %s */\n", nm, comment);
    for (q = 0; q < 4; q++) {
        ox = (q & 1) ? 8 : 0;
        oy = (q & 2) ? 8 : 0;
        printf("    ");
        for (r = 0; r < 8; r++) {
            b = 0;
            for (x = 0; x < 8; x++)
                b = (b << 1) | (B[oy + r][ox + x] & 1);
            printf("0x%02X%s", b, (q == 3 && r == 7) ? "" : ",");
        }
        printf("   /* %s */\n", lab[q]);
    }
    printf("};\n");
}

/* squared distance from the cell centre (7.5,7.5), in 2x units (so it stays int) */
static int r2c(int x, int y)
{
    int dx = 2 * x - 15, dy = 2 * y - 15;
    return dx * dx + dy * dy;
}

/* Round donut token: filled disc with a transparent centre hole (the hole shows
 * the cell/field colour, reading as a pip). */
static void token(void)
{
    int x, y, d;
    clear();
    for (y = 0; y < 16; y++)
        for (x = 0; x < 16; x++) {
            d = r2c(x, y);
            if (d <= 225 && d >= 49) B[y][x] = 1;   /* ring: r ~3.5 .. 7.5 */
        }
}

/* Gold bullseye eye: a thin outer ring + a solid centre pearl. */
static void eye(void)
{
    int x, y, d;
    clear();
    for (y = 0; y < 16; y++)
        for (x = 0; x < 16; x++) {
            d = r2c(x, y);
            if (d <= 225 && d >= 121) B[y][x] = 1;  /* outer ring r ~5.5..7.5 */
            if (d <= 36)              B[y][x] = 1;   /* centre pearl r ~3     */
        }
}

/* Quincunx: a 1px border frame with five 2x2 studs (4 corners + centre). */
static void dots(void)
{
    int x, y;
    static const int cx[5] = { 3, 11, 7, 3, 11 };
    static const int cy[5] = { 3, 3, 7, 11, 11 };
    int i, sx, sy;
    clear();
    for (y = 0; y < 16; y++)
        for (x = 0; x < 16; x++)
            if (x == 0 || x == 15 || y == 0 || y == 15)
                B[y][x] = 1;                          /* border frame */
    for (i = 0; i < 5; i++)
        for (sy = 0; sy < 2; sy++)
            for (sx = 0; sx < 2; sx++)
                B[cy[i] + sy][cx[i] + sx] = 1;        /* 2x2 studs */
}

/* Eight-petal gold rosette flower: a round body with 8 notched petal gaps. */
static void rose(void)
{
    int x, y, d;
    clear();
    for (y = 0; y < 16; y++)
        for (x = 0; x < 16; x++) {
            d = r2c(x, y);
            if (d > 225) continue;                    /* outside the bloom */
            /* notch 8 petal gaps: cut near the 45-degree diagonals in an
             * annulus so the rim reads as separate petals, keep a solid core */
            if (d > 100) {
                int dx = 2 * x - 15, dy = 2 * y - 15;
                int ax = dx < 0 ? -dx : dx, ay = dy < 0 ? -dy : dy;
                int diff = ax - ay; if (diff < 0) diff = -diff;
                if (diff < 6) continue;               /* petal gap */
            }
            B[y][x] = 1;
        }
    B[7][7] = B[7][8] = B[8][7] = B[8][8] = 0;        /* tiny centre pip */
}

int main(void)
{
    printf("/* Generated by tools/adam-mosaic-glyphs.c -- do not hand-edit. */\n");
    rose();   emit("rose_cell", "8-petal gold rosette + pip");
    eye();    emit("eye_cell",  "gold bullseye: ring + pearl");
    dots();   emit("dots_cell", "bordered five-dot quincunx");
    token();  emit("tok_cell",  "round token donut (hole = pip)");
    printf("static const unsigned char g_bead[8] = "
           "{ 0x3C,0x7E,0xFF,0xFF,0xFF,0xFF,0x7E,0x3C }; /* tray bead */\n");
    return 0;
}
